site_name: Fase
site_url: http://fase.io/
copyright: 2018 Fase &trade;
nav:
    - 'Index': 'index.md'
    - 'Example: Notes Service': 'notes_service.md'
    - 'Example: KarmaCounter': 'karmacounter.md'
theme: readthedocs

